### ISSUE TITLE
Interactive example

### ISSUE THREAD

**Issue by Vrixyz** [vleue/polyanya#2]
# Goal

Provide an example showcasing pathfinding interactivity.

Something as simple as possible, 2D, working on wasm should be the objective.

## Existing work

Below showcases a 3d interactivity, which code might be relevant: https://github.com/Vrixyz/meshquisse)

https://user-images.githubusercontent.com/2290685/190685401-84994a79-e825-40f2-ba54-2ac12737fa6f.mp4

**Comment by mockersf** [comment]
done at https://vleue.github.io/bevy_pathmesh/
