### ISSUE TITLE
error if obstacles overlap all of the initial outer boundary

### ISSUE THREAD

**Issue by AnAverageGitUser** [vleue/polyanya#47]
I'm was getting errornous behaviour if error if obstacles overlap all of the initial outer boundary of the Polyana::Triangulation.
This resulted in an empty navmesh, because the merge_obstacle function has/had an error/wasn't intended to handle this case.
I think I solved this problem, althought I'm not sure if you want the changes there to be merged upstream, you might want some changes to be done.

Anyway if anyone has a similar problem, for the time beeing you can check if the branch/commit here is doing what you want: https://github.com/vleue/polyanya/compare/main...AnAverageGitUser:polyanya:aagu/myapp current commit 82f2ec70ab30a23983c516b50183f87349c146df

**Comment by mockersf** [comment]
fixed in #53
