### ISSUE TITLE
Obstacles with holes

### ISSUE THREAD

**Issue by 0x0539** [vleue/polyanya#77]
It seems like obstacles are mostly "solid" in the examples. Is it possible to have an obstacle with a hole, where navigation can be done inside the hole or outside the obstacle but not across? 

Does it require multiple layers?

**Comment by 0x0539** [comment]
I resolved this by organizing by polygons into a container->contained hierarchy (using a ray-casting algorithm) and creating a polyanya layer for each polygon where the children get added to the parent as obstacles and stitching along the boundaries.

**Comment by mockersf** [comment]
It should be possible to do it with only one layer. There's no way to define an obstacle with an hole inside, but splitting the obstacle into smaller for each side that overlap should work
